# Generated by Django 5.0.4 on 2024-06-12 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibles',
            options={'managed': True},
        ),
    ]
