# Generated by Django 5.0.4 on 2024-06-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0002_alter_bibles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibles',
            options={'managed': False},
        ),
    ]
