# Generated by Django 5.0.4 on 2024-06-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleapp', '0003_alter_bibles_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allbibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bible', models.TextField(blank=True, db_column='Bible', null=True)),
                ('idbible', models.TextField(blank=True, db_column='idBible', null=True)),
                ('vid', models.IntegerField(blank=True, null=True)),
                ('b', models.IntegerField(blank=True, null=True)),
                ('c', models.IntegerField(blank=True, null=True)),
                ('v', models.IntegerField(blank=True, null=True)),
                ('t', models.TextField(blank=True, null=True)),
                ('book', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'allbibles',
                'managed': False,
            },
        ),
    ]
